检测间隔: 1
模板配置:
  准备就绪:
    路径: "templates/ready.png"
    偏移: [0, 0]
  返回:
    路径: "templates/back.png"
    偏移: [0, 0]
  武器选择:
    路径: "templates/select.png"
    默认偏移: [0, 200]
    武器模板目录: "templates/weapons"
    成功偏移: [0, 0]
